name: Run Fivetran Debug

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fivetran-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fivetran_connector_sdk

      - name: Run Fivetran Debug
        env:
          TEST_KEY: ${{ secrets.SATVIK_API_TEST }}
        working-directory: examples/quickstart_examples/hello  
        run: |
          set -e
          echo "Starting Fivetran deployment"

          python3 -u -c "
          import subprocess, sys
          try:
              print('Running fivetran deploy...', flush=True)
              result = subprocess.run([
                  'fivetran', 'deploy',
                  '--api-key', '${TEST_KEY}',
                  '--destination', 'Testing',
                  '--connection', 'satvik_csdk_test_github_action',
                  '--python-version', '3.11.11',
                  '--force'
              ], capture_output=True, text=True)
              print(result.stdout)
              print(result.stderr, file=sys.stderr)
              if result.returncode != 0:
                  print('Deploy failed with exit code', result.returncode, file=sys.stderr)
                  sys.exit(result.returncode)
          except Exception as e:
              print(f'Error occurred: {e}', file=sys.stderr)
              sys.exit(1)
          "
