name: Run Fivetran Debug

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fivetran-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fivetran_connector_sdk

      - name: Run Fivetran Debug
        env:
          TEST_KEY: ${{ secrets.SATVIK_API_TEST }}
        working-directory: examples/quickstart_examples/hello  
        run: |
          set -o pipefail

          # echo "Approach 1: Starting Fivetran deploy..."
      
          # script -q -e -c "fivetran deploy \
          #   --api-key $TEST_KEY \
          #   --destination 'Testing' \
          #   --connection 'satvik_csdk_test_github_action' \
          #   --python-version '3.11.11' \
          #   --force" fivetran_deploy.log
      
          # status=$?
          # cat fivetran_deploy.log
      
          # if [ "$status" -ne 0 ]; then
          #   echo "❌ Fivetran deploy failed with status $status"
          #   exit $status
          # else
          #   echo "✅ Fivetran deploy succeeded"
          # fi

          echo "Using Approach 2: Starting Fivetran deploy..."
          
          fivetran deploy \
          --api-key $TEST_KEY \
          --destination 'Testing' \
          --connection 'satvik_csdk_test_github_action' \
          --python-version '3.11.11' \
          --force 2>&1 | tee fivetran_deploy.log
    
          status=${PIPESTATUS[0]}
          cat fivetran_deploy.log
      
          if [ "$status" -ne 0 ]; then
            echo "❌ Fivetran deploy failed with status $status"
            exit $status
          fi
