name: Run Fivetran Debug

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fivetran-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fivetran_connector_sdk

      - name: Run Fivetran Debug
        working-directory: examples/quickstart_examples/hello  
        run: |
          echo "Running in directory: $(pwd)"
          ls
          echo "----------"
          cat connector.py
          echo "----------"
          fivetran deploy --api-key 1348qfwdfjasdfkjasdf == --destination "Testing" --connection satvik_csdk_action_test
