name: Run Fivetran Debug

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  fivetran-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fivetran_connector_sdk

      - name: Run Fivetran Debug
        env:
          TEST_KEY: ${{ secrets.SATVIK_API_TEST }}
        working-directory: examples/quickstart_examples/hello  
        run: |
          echo "Running Fivetran Deploy..."
          fivetran deploy \
            --api-key $API_TEST \
            --destination "Testing" \
            --connection "satvik_csdk_testing_github_action" \
            --python-version "3.11" \
            --force 
          # exit_code=$?
          
          # echo "$output"
      
          # if [ $exit_code -ne 0 ]; then
          #   echo "Fivetran deploy failed with exit code $exit_code"
          #   exit $exit_code
          # fi
